// ─── Comprehensive Government Knowledge Base ──────────────────
// Every service, scheme, and piece of information a citizen might need
// This is the verified source of truth for OneGov AI

export interface KnowledgeEntry {
  id: string;
  type: "service" | "scheme" | "info" | "grievance" | "rights";
  name: string;
  nameHindi?: string;
  department: string;
  description: string;
  keywords: string[];
  eligibility?: string[];
  benefits?: string[];
  requiredDocuments?: string[];
  requiredFields?: string[];
  prerequisites?: string[];
  estimatedDays?: number;
  officialPortal?: string;
  helpline?: string;
  fee?: string;
  category: string;
}

export const COMPREHENSIVE_KNOWLEDGE: KnowledgeEntry[] = [
  // ═══════════════════════════════════════════════════════════════
  // IDENTITY DOCUMENTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "svc-aadhaar",
    type: "service",
    name: "Aadhaar Card",
    nameHindi: "आधार कार्ड",
    department: "Unique Identification Authority of India (UIDAI)",
    description: "Aadhaar is a 12-digit unique identity number issued by UIDAI to residents of India based on biometric and demographic data. It is the world's largest biometric ID system.",
    keywords: ["aadhaar", "aadhaar card", "uidai", "unique id", "biometric", "aadhaar update", "aadhaar enrollment", "aadhaar correction", "aadhaar number", "aadhaar linked", "aadhaar verification"],
    eligibility: ["Any resident of India", "No age restriction", "Minors need parent/guardian consent"],
    benefits: ["Used as identity proof across India", "Linked to bank accounts, PAN, LPG subsidy", "Required for many government schemes", "Address update possible online"],
    requiredDocuments: ["Identity proof (any valid document)", "Address proof", "Date of birth proof", "Existing Aadhaar (for update)"],
    estimatedDays: 15,
    officialPortal: "https://uidai.gov.in",
    helpline: "1947",
    fee: "₹50 for update, Free for new enrollment",
    category: "identity",
  },
  {
    id: "svc-pan",
    type: "service",
    name: "PAN Card",
    nameHindi: "पैन कार्ड",
    department: "Income Tax Department (via NSDL/UTIITSL)",
    description: "Permanent Account Number (PAN) is a 10-digit alphanumeric identifier issued by the Income Tax Department. Required for financial transactions, tax filing, and business registration.",
    keywords: ["pan", "pan card", "pan number", "nsdl", "utiitsl", "income tax", "permanent account number", "pan application", "pan correction", "pan reprint", "pan link aadhaar"],
    eligibility: ["Indian citizens", "Indian companies/entities", "Anyone who pays income tax", "Required for transactions above ₹50,000"],
    benefits: ["Required for income tax filing", "Needed for business registration", "Required for bank accounts above certain limits", "Used for property transactions"],
    requiredDocuments: ["Identity proof (Aadhaar/Voter ID/Passport)", "Address proof", "Passport-size photograph", "Date of birth proof"],
    estimatedDays: 7,
    officialPortal: "https://www.onlineservices.nsdl.com",
    helpline: "1800-103-0031",
    fee: "₹107 (online Indian address) / ₹1,020 (foreign address)",
    category: "identity",
  },
  {
    id: "svc-passport",
    type: "service",
    name: "Passport",
    nameHindi: "पासपोर्ट",
    department: "Passport Seva, Ministry of External Affairs",
    description: "Apply for an Indian passport for international travel. Available as fresh passport, renewal, reissue, or tatkal (urgent) passport.",
    keywords: ["passport", "passport application", "passport renewal", "passport seva", "travel document", "international travel", "new passport", "reissue passport", "tatkal passport", "passport police verification", "passport office", "psk"],
    eligibility: ["Indian citizens", "Minors need parent consent", "ECR/ECNR categories based on education"],
    benefits: ["Proof of Indian citizenship abroad", "Required for international travel", "Used as ID proof", "Valid in 199 countries"],
    requiredDocuments: ["Aadhaar card", "PAN card", "Address proof", "Photograph (passport size)", "Birth certificate or age proof", "Old passport (for renewal)"],
    prerequisites: ["Aadhaar recommended", "PAN recommended"],
    estimatedDays: 14,
    officialPortal: "https://www.passportindia.gov.in",
    helpline: "1800-258-1800",
    fee: "₹1,500 (36 pages) / ₹2,000 (60 pages) / ₹3,500 (Tatkal)",
    category: "identity",
  },
  {
    id: "svc-dl",
    type: "service",
    name: "Driving License",
    nameHindi: "ड्राइविंग लाइसेंस",
    department: "Ministry of Road Transport & Highways (Parivahan)",
    description: "Apply for a learner's or permanent driving license through Parivahan Sewa. Available for two-wheeler, four-wheeler, and commercial vehicles.",
    keywords: ["driving license", "dl", "learner license", "permanent license", "parivahan", "vehicle", "driving", "transport", "car license", "bike license", "motor driving", "driving test", "licence renewal"],
    eligibility: ["Age 18+ for transport vehicles", "Age 16+ for non-transport (with parent consent)", "Medically fit", "Learner's license holder for 30+ days"],
    requiredDocuments: ["Aadhaar card", "Address proof", "Age proof", "Medical certificate (Form 1A)", "Passport-size photographs", "Learner's license (for permanent DL)"],
    estimatedDays: 10,
    officialPortal: "https://parivahan.gov.in",
    helpline: "1800-11-0031",
    fee: "₹200 (learner) / ₹1,000 (permanent) / ₹200 (renewal)",
    category: "transport",
  },
  {
    id: "svc-voter",
    type: "service",
    name: "Voter ID Registration",
    nameHindi: "मतदाता पहचान पत्र",
    department: "Election Commission of India (ECI)",
    description: "Register as a voter or update your Voter ID details through the National Voters' Service Portal (NVSP). Every Indian citizen aged 18+ has the right to vote.",
    keywords: ["voter", "voter id", "election", "voting", "electoral", "nvsp", "voter registration", "voter card", "election commission", "voter correction", "voter address change", "new voter id"],
    eligibility: ["Indian citizen", "Age 18 or above on January 1 of the year", "Ordinary resident of the constituency"],
    requiredDocuments: ["Aadhaar card", "Address proof", "Photograph", "Age proof"],
    estimatedDays: 15,
    officialPortal: "https://www.nvsp.in",
    helpline: "1950",
    fee: "Free",
    category: "identity",
  },

  // ═══════════════════════════════════════════════════════════════
  // BUSINESS & TAX
  // ═══════════════════════════════════════════════════════════════
  {
    id: "svc-business-reg",
    type: "service",
    name: "Business Registration",
    nameHindi: "व्यापार पंजीकरण",
    department: "Ministry of Corporate Affairs (MCA)",
    description: "Register your business entity (Private Limited, LLP, Partnership, Sole Proprietorship) with the Ministry of Corporate Affairs.",
    keywords: ["business", "company", "register", "startup", "enterprise", "firm", "private limited", "llp", "partnership", "sole proprietorship", "mca", "incorporation", "business entity", "company registration", "pvt ltd", "opc"],
    eligibility: ["Indian citizen or entity", "Valid identity proof", "Registered business address in India"],
    requiredDocuments: ["Identity proof (Aadhaar/PAN)", "Address proof", "Business plan or memorandum", "Partners/directors ID proof", "Office address proof"],
    prerequisites: ["PAN card for all directors/partners", "Digital Signature Certificate (DSC)"],
    estimatedDays: 7,
    officialPortal: "https://www.mca.gov.in",
    fee: "₹5,000 - ₹15,000 depending on type",
    category: "business",
  },
  {
    id: "svc-gst",
    type: "service",
    name: "GST Registration",
    nameHindi: "जीएसटी पंजीकरण",
    department: "Goods and Services Tax Network (GSTN)",
    description: "Register for Goods and Services Tax (GST) to legally collect tax on sales and claim input tax credits. Mandatory for businesses with turnover above ₹40 lakh.",
    keywords: ["gst", "tax", "goods and services tax", "tax registration", "gstn", "tax number", "gst number", "input tax", "tax filing", "business tax", "gst return", "gst registration", "gst portal"],
    eligibility: ["Business with turnover above ₹40 lakh (₹20 lakh for NE states)", "Inter-state suppliers", "E-commerce operators", "TDS/TCS deductors"],
    requiredDocuments: ["PAN card", "Aadhaar card", "Business registration certificate", "Address proof", "Bank account details", "Photograph"],
    prerequisites: ["Completed business registration", "PAN card"],
    estimatedDays: 5,
    officialPortal: "https://www.gst.gov.in",
    helpline: "1800-103-4786",
    fee: "Free",
    category: "tax",
  },
  {
    id: "svc-fssai",
    type: "service",
    name: "FSSAI Food License",
    nameHindi: "एफएसएसएआई खाद्य लाइसेंस",
    department: "Food Safety and Standards Authority of India (FSSAI)",
    description: "Obtain food safety license required for any food business including restaurants, cafes, food stalls, cloud kitchens, and food manufacturing.",
    keywords: ["food", "fssai", "restaurant", "cafe", "food license", "food business", "food safety", "dining", "eatery", "food stall", "cloud kitchen", "catering", "food shop", "bakery", "hotel food", "street food", "food manufacturing", "food processing"],
    eligibility: ["Any food business operator in India", "Turnover above ₹12 lakh: state license", "Turnover above ₹20 crore: central license"],
    requiredDocuments: ["Business registration", "PAN card", "Layout plan", "Health certificates", "Food product list", "Water test report"],
    prerequisites: ["Completed business registration", "PAN card", "Physical premises"],
    estimatedDays: 21,
    officialPortal: "https://www.fssai.gov.in",
    helpline: "1800-11-2100",
    fee: "₹2,000 - ₹7,500 depending on turnover",
    category: "food",
  },
  {
    id: "svc-income-cert",
    type: "service",
    name: "Income Certificate",
    nameHindi: "आय प्रमाण पत्र",
    department: "Revenue Department / Tehsildar Office",
    description: "Obtain income certificate for government schemes, subsidies, educational admissions, and scholarship applications.",
    keywords: ["income certificate", "income proof", "salary certificate", "income verification", "government scheme", "subsidy", "scholarship", "income proof for", "aay praman patra"],
    eligibility: ["Any Indian citizen"],
    requiredDocuments: ["Aadhaar card", "Salary slips or income proof", "Bank statement", "Affidavit"],
    estimatedDays: 7,
    fee: "₹10 - ₹50",
    category: "civil",
  },
  {
    id: "svc-caste-cert",
    type: "service",
    name: "Caste Certificate",
    nameHindi: "जाति प्रमाण पत्र",
    department: "Revenue Department / Tehsildar Office",
    description: "Obtain caste certificate for reservation benefits in education, employment, and government schemes. Required for SC/ST/OBC candidates.",
    keywords: ["caste certificate", "caste proof", "sc st obc certificate", "reservation", "jati praman patra", "sc certificate", "st certificate", "obc certificate", "ews certificate", "economically weaker section"],
    eligibility: ["Indian citizens belonging to SC/ST/OBC/EWS categories"],
    requiredDocuments: ["Aadhaar card", "School leaving certificate", "Parent's caste certificate", "Affidavit"],
    estimatedDays: 10,
    fee: "₹10 - ₹50",
    category: "civil",
  },
  {
    id: "svc-ration",
    type: "service",
    name: "Ration Card",
    nameHindi: "राशन कार्ड",
    department: "Department of Food & Public Distribution",
    description: "Apply for a new ration card or add family members. Ration card provides subsidized food grains under the National Food Security Act.",
    keywords: ["ration card", "ration", "food card", "bpl card", "antyodaya", "priority household", "nfsa", "subsidized food", "food security", "pds", "ration card apply", "add family member ration"],
    eligibility: ["Indian families", "BPL families get Antyodaya cards", "APL families get Priority Household cards"],
    requiredDocuments: ["Aadhaar card (all family members)", "Address proof", "Income certificate", "Family photograph", "Old ration card (if applicable)"],
    estimatedDays: 15,
    fee: "Free",
    category: "welfare",
  },
  {
    id: "svc-property",
    type: "service",
    name: "Property Registration",
    nameHindi: "संपत्ति पंजीकरण",
    department: "Sub-Registrar Office / Revenue Department",
    description: "Register property sale deed at the Sub-Registrar Office for legal ownership transfer. Mandatory for all property transactions in India.",
    keywords: ["property", "registration", "sale deed", "land", "house", "flat", "real estate", "sub registrar", "stamp duty", "property transfer", "buy property", "property purchase", "property sale", "mutation"],
    requiredDocuments: ["Sale deed (original)", "Property tax receipts", "NOC", "Identity proof of both parties", "Stamp duty receipt", "Encumbrance certificate", "Mother deed"],
    prerequisites: ["Stamp duty payment", "Valuation certificate"],
    estimatedDays: 3,
    fee: "Stamp duty: 5-7% of property value + registration fee",
    category: "property",
  },
  {
    id: "svc-7-12",
    type: "service",
    name: "7/12 Extract & Property Card",
    nameHindi: "७/१२ उतारा",
    department: "Revenue Department / Maharashtra",
    description: "View and obtain 7/12 extract (satbara) and property card from Maharashtra revenue department. Shows land ownership and cultivation details.",
    keywords: ["7/12", "satbara", "property card", "land record", "land ownership", "property extract", "bhulekh", "land details", "zameen", "jameen"],
    estimatedDays: 1,
    officialPortal: "https://digitize.mahabhumi.gov.in",
    fee: "₹10 - ₹25",
    category: "property",
  },

  // ═══════════════════════════════════════════════════════════════
  // CIVIL DOCUMENTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "svc-birth-cert",
    type: "service",
    name: "Birth Certificate",
    nameHindi: "जन्म प्रमाण पत्र",
    department: "Municipal Corporation",
    description: "Register birth and obtain birth certificate from the local Municipal Corporation. Mandatory for school admission, passport, and identity proof.",
    keywords: ["birth certificate", "birth registration", "janam praman patra", "child birth", "newborn", "birth record", "birth proof"],
    requiredDocuments: ["Hospital birth record", "Parents' identity proof", "Parents' marriage certificate"],
    eligibility: ["Parents of newborn child", "Within 21 days of birth (normal registration)", "Delayed registration possible with affidavit"],
    estimatedDays: 7,
    fee: "₹5 - ₹25",
    category: "civil",
  },
  {
    id: "svc-death-cert",
    type: "service",
    name: "Death Certificate",
    nameHindi: "मृत्यु प्रमाण पत्र",
    department: "Municipal Corporation",
    description: "Register death and obtain death certificate. Required for insurance claims, property transfer, and legal purposes.",
    keywords: ["death certificate", "death registration", "mrityu praman patra", "death record"],
    requiredDocuments: ["Hospital record", "Applicant identity proof"],
    estimatedDays: 7,
    fee: "₹5 - ₹25",
    category: "civil",
  },
  {
    id: "svc-marriage",
    type: "service",
    name: "Marriage Registration",
    nameHindi: "विवाह पंजीकरण",
    department: "Municipal Corporation / Sub-Registrar",
    description: "Register marriage under the Special Marriage Act or Hindu Marriage Act. Provides legal recognition of marriage.",
    keywords: ["marriage", "marriage registration", "wedding", "shadi", "vivah", "marriage certificate", "registered marriage", "marriage registrar"],
    requiredDocuments: ["Both partners' identity proof", "Address proof", "Photographs", "Witness identity proof (2)", "Marriage invitation", "Affidavit"],
    eligibility: ["Groom age 21+, Bride age 18+", "Both parties consenting"],
    estimatedDays: 7,
    fee: "₹100 - ₹500",
    category: "civil",
  },

  // ═══════════════════════════════════════════════════════════════
  // WELFARE SCHEMES
  // ═══════════════════════════════════════════════════════════════
  {
    id: "sch-pmkisan",
    type: "scheme",
    name: "PM-KISAN",
    nameHindi: "पीएम-किसान",
    department: "Ministry of Agriculture & Farmers Welfare",
    description: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) provides income support of ₹6,000 per year to small and marginal farmer families through direct benefit transfer.",
    keywords: ["pm kisan", "pm-kisan", "kisan", "farmer", "agriculture", "fpo", "income support", "direct benefit", "dbt", "kisan samman nidhi", "pm kisan yojana", "kisan credit card"],
    eligibility: ["Small and marginal farmer families", "Land holding up to 2 hectares", "Must have Aadhaar linked bank account", "Not for institutional landholders, ex-MPs/MLAs, government employees"],
    benefits: ["₹6,000 per year in 3 installments of ₹2,000 each", "Direct transfer to bank account", "No application fee"],
    requiredDocuments: ["Aadhaar card", "Bank account details", "Land records (Khata/Khasra number)"],
    officialPortal: "https://pmkisan.gov.in",
    helpline: "1800-180-1551",
    fee: "Free",
    category: "welfare",
  },
  {
    id: "sch-ayushman",
    type: "scheme",
    name: "Ayushman Bharat (PMJAY)",
    nameHindi: "आयुष्मान भारत",
    department: "Ministry of Health & Family Welfare",
    description: "Pradhan Mantri Jan Arogya Yojana (PM-JAY) provides health insurance cover of ₹5 lakh per family per year for secondary and tertiary hospitalization.",
    keywords: ["ayushman bharat", "pmjay", "health insurance", "health cover", "hospital", "medical", "treatment", "surgery", "free treatment", "government hospital", "health scheme", "5 lakh", "medical insurance"],
    eligibility: ["Families identified in SECC 2011 database", "Rural: BPL families", "Urban: 11 occupational categories", "No income ceiling for SC/ST households"],
    benefits: ["₹5 lakh per family per year", "Covers 1,929 medical packages", "Cashless and paperless at point of service", "Covers pre and post hospitalization expenses"],
    requiredDocuments: ["Ration card or SECC identification", "Aadhaar card", "Any photo ID"],
    officialPortal: "https://mera.pmjay.gov.in",
    helpline: "14555 / 1800-111-565",
    fee: "Free",
    category: "welfare",
  },
  {
    id: "sch-ujjwala",
    type: "scheme",
    name: "Ujjwala Yojana",
    nameHindi: "उज्ज्वला योजना",
    department: "Ministry of Petroleum & Natural Gas",
    description: "Pradhan Mantri Ujjwala Yojana provides free LPG connections to women from BPL families, reducing indoor air pollution from cooking fuels.",
    keywords: ["ujjwala", "ujjwala yojana", "lpg", "gas connection", "free gas", "cooking gas", "bpl gas", "ujjwala connection"],
    eligibility: ["BPL women aged 18+", "No existing LPG connection in household", "SC/ST/BC/EWS households priority"],
    benefits: ["Free LPG connection", "First refill free", "Safety training"],
    requiredDocuments: ["BPL certificate or ration card", "Aadhaar card", "Bank account details", "Passport-size photograph"],
    officialPortal: "https://www.pmujjwalayojana.in",
    fee: "Free",
    category: "welfare",
  },
  {
    id: "sch-jandhan",
    type: "scheme",
    name: "Jan Dhan Yojana",
    nameHindi: "जन धन योजना",
    department: "Ministry of Finance",
    description: "Pradhan Mantri Jan Dhan Yojana provides zero-balance bank accounts to unbanked citizens, enabling financial inclusion and direct benefit transfers.",
    keywords: ["jan dhan", "jan dhan yojana", "bank account", "zero balance", "financial inclusion", "dbt", "aadhaar linked", "pmjdby", "rupee card"],
    eligibility: ["Any Indian citizen", "No existing bank account needed", "Minors (10+) can open with guardian"],
    benefits: ["Zero balance account", "Free RuPay debit card", "₹2 lakh accident insurance", "Overdraft facility up to ₹10,000", "Direct benefit transfer eligible"],
    requiredDocuments: ["Aadhaar card (if available)", "Any valid ID proof", "Passport-size photograph", "Address proof"],
    fee: "Free",
    category: "welfare",
  },
  {
    id: "sch-mudra",
    type: "scheme",
    name: "MUDRA Loan",
    nameHindi: "मुद्रा ऋण",
    department: "Small Industries Development Bank of India (SIDBI)",
    description: "Micro Units Development & Refinance Agency (MUDRA) provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises.",
    keywords: ["mudra", "mudra loan", "business loan", "small loan", "micro loan", "shishu", "kishore", "tarun", "startup loan", "msme loan"],
    eligibility: ["Non-corporate, non-farm small/micro enterprises", "Manufacturing, trading, services sectors", "Individuals, proprietorships, partnership firms"],
    benefits: ["Shishu: up to ₹50,000", "Kishore: ₹50,001 to ₹5 lakh", "Tarun: ₹5,00,001 to ₹10 lakh", "No collateral required", "Subsidized interest rates"],
    requiredDocuments: ["Identity proof", "Address proof", "Business plan/Project report", "Quotations for machinery/equipment", "Bank statements (if existing business)"],
    officialPortal: "https://www.mudra.org.in",
    fee: "Free processing",
    category: "welfare",
  },
  {
    id: "sch-msme",
    type: "scheme",
    name: "MSME Registration",
    nameHindi: "एमएसएमई पंजीकरण",
    department: "Ministry of Micro, Small & Medium Enterprises",
    description: "Register your Micro, Small or Medium Enterprise under the MSMED Act to access government subsidies, priority sector lending, and tax benefits.",
    keywords: ["msme", "msme registration", "udyam", "udyam registration", "small business", "micro enterprise", "small enterprise", "medium enterprise", "udyog aadhaar"],
    eligibility: ["Manufacturing enterprises: investment up to ₹250 crore", "Service enterprises: turnover up to ₹200 crore"],
    benefits: ["Priority sector lending", "Government subsidies", "Tax benefits", "Protection against delayed payments", "Ease of doing business"],
    requiredDocuments: ["Aadhaar card", "PAN card", "Business address proof", "Bank account details", "Investment details"],
    officialPortal: "https://udyamregistration.gov.in",
    fee: "Free",
    category: "welfare",
  },

  // ═══════════════════════════════════════════════════════════════
  // GOVERNMENT RIGHTS & PROCEDURES
  // ═══════════════════════════════════════════════════════════════
  {
    id: "info-rti",
    type: "rights",
    name: "Right to Information (RTI)",
    nameHindi: "सूचना का अधिकार",
    department: "Ministry of Personnel, Public Grievances & Pensions",
    description: "The Right to Information Act, 2005 empowers every Indian citizen to request information from public authorities. Government must respond within 30 days.",
    keywords: ["rti", "right to information", "rti act", "rti application", "information", "transparency", "government information", "rti fee", "rti online", "public authority", "cic", "sic", "first appeal", "second appeal", "proactive disclosure"],
    eligibility: ["Any Indian citizen", "No income restriction", "Can be filed for any public authority"],
    benefits: ["Access to government records", "Accountability of public officials", "Transparency in governance", "Fight corruption"],
    requiredDocuments: ["RTI application (plain paper)", "Identity proof", "₹10 court fee stamp or IPO"],
    officialPortal: "https://rtionline.gov.in",
    helpline: "1800-11-0031",
    fee: "₹10 application fee",
    category: "rights",
  },
  {
    id: "info-grievance",
    type: "grievance",
    name: "Public Grievance Portal (CPGRAMS)",
    nameHindi: "जन शिकायत पोर्टल",
    department: "Department of Administrative Reforms & Public Grievances",
    description: "Centralized Public Grievance Redress and Monitoring System (CPGRAMS) allows citizens to file grievances against any central government ministry or department.",
    keywords: ["grievance", "complaint", "cpgrams", "public grievance", "shikayat", "complaint portal", "file complaint", "government complaint", "redressal", "ombudsman", "lokpala"],
    eligibility: ["Any Indian citizen", "Complaint against central government ministry/department"],
    benefits: ["Online complaint filing", "Track complaint status", "Escalation mechanism", "Time-bound resolution (30 days)"],
    requiredDocuments: ["Description of grievance", "Supporting documents (if any)", "Identity proof"],
    officialPortal: "https://pgportal.gov.in",
    fee: "Free",
    category: "grievance",
  },
  {
    id: "info-consumer",
    type: "rights",
    name: "Consumer Protection",
    nameHindi: "उपभोक्ता संरक्षण",
    department: "Ministry of Consumer Affairs, Food & Public Distribution",
    description: "The Consumer Protection Act, 2019 provides rights to consumers against defective goods, deficient services, and unfair trade practices.",
    keywords: ["consumer", "consumer protection", "consumer court", "consumer complaint", "defective product", "refund", "replacement", "consumer rights", "national consumer helpline", "consumer forum", "e-daakhil"],
    eligibility: ["Any consumer who has purchased goods/services for consideration", "Includes online purchases"],
    benefits: ["File complaints online (e-Daakhil)", "Consumer courts at district/state/national level", "Compensation for deficiency", "Product liability provisions"],
    officialPortal: "https://edaakhil.nic.in",
    helpline: "1800-11-4000",
    fee: "₹100 - ₹5,000 depending on claim value",
    category: "rights",
  },
  {
    id: "info-labour",
    type: "info",
    name: "Labour Rights & Worker Protections",
    nameHindi: "श्रमिक अधिकार",
    department: "Ministry of Labour & Employment",
    description: "Four Labour Codes consolidate 29 labour laws into 4 codes: Wages, Social Security, Industrial Relations, and Occupational Safety.",
    keywords: ["labour", "worker", "employee", "minimum wage", "epfo", "esi", "pf", "provident fund", "gratuity", "bonus", "labour law", "worker rights", "factory", "workplace safety", "maternity benefit", "contract worker"],
    eligibility: ["All workers in organized and unorganized sectors", "Minimum wage applicable for all"],
    benefits: ["Minimum wage guarantee", "Provident fund (EPFO)", "Employee state insurance (ESI)", "Maternity benefit (26 weeks)", "Gratuity after 5 years", "Workplace safety standards"],
    officialPortal: "https://labour.gov.in",
    helpline: "1800-11-0031",
    category: "info",
  },

  // ═══════════════════════════════════════════════════════════════
  // EDUCATION & SCHOLARSHIPS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "sch-scholarship",
    type: "scheme",
    name: "National Scholarship Portal",
    nameHindi: "राष्ट्रीय छात्रवृत्ति पोर्टल",
    department: "Ministry of Electronics & Information Technology",
    description: "One-stop platform for students to apply for scholarships from Central Government, State Governments, and UGC/AICTE.",
    keywords: ["scholarship", "student", "education", "nsP", "national scholarship portal", "pre matric", "post matric", "merit scholarship", "minority scholarship", "sc scholarship", "st scholarship", "obc scholarship", "girl child scholarship", "education loan"],
    eligibility: ["Students from class 1 to PhD", "SC/ST/OBC/Minority/EWS categories", "Family income criteria vary by scheme"],
    benefits: ["Fee reimbursement", "Monthly stipend", "Book grant", "Multiple scholarships available"],
    requiredDocuments: ["Aadhaar card", "Bank account details", "Income certificate", "Caste certificate (if applicable)", "Previous year marksheet", "Institution admission letter"],
    officialPortal: "https://scholarships.gov.in",
    fee: "Free",
    category: "welfare",
  },
  {
    id: "info-education",
    type: "info",
    name: "Right to Education (RTE)",
    nameHindi: "शिक्षा का अधिकार",
    department: "Ministry of Education",
    description: "The Right of Children to Free and Compulsory Education Act, 2009 guarantees free and compulsory education to all children aged 6-14 years.",
    keywords: ["education", "rte", "right to education", "school admission", "free education", "compulsory education", "primary education", "elementary education", "school", "admission", "25% reservation"],
    eligibility: ["All children aged 6-14 years", "25% seats in private schools reserved for BPL children"],
    benefits: ["Free and compulsory education", "No detention until class 8", "Free textbooks, uniforms, mid-day meal", "25% reservation in private schools"],
    category: "info",
  },

  // ═══════════════════════════════════════════════════════════════
  // HOUSING & SANITATION
  // ═══════════════════════════════════════════════════════════════
  {
    id: "sch-pmay",
    type: "scheme",
    name: "PM Awas Yojana",
    nameHindi: "पीएम आवास योजना",
    department: "Ministry of Housing & Urban Affairs",
    description: "Pradhan Mantri Awas Yojana provides affordable housing to urban poor with credit-linked subsidy. Target: Housing for All by 2024.",
    keywords: ["pm awas", "pmay", "housing", "affordable housing", "home loan", "housing subsidy", "credit linked subsidy", "house for all", "urban housing", "rural housing", "gruh lakshmi"],
    eligibility: ["EWS: family income up to ₹3 lakh", "LIG: ₹3-6 lakh", "MIG-I: ₹6-12 lakh", "MIG-II: ₹12-18 lakh", "No pucca house in family"],
    benefits: ["Credit-linked subsidy up to ₹2.67 lakh", "Interest subsidy on home loan", "Direct benefit transfer"],
    requiredDocuments: ["Aadhaar card", "Income certificate", "Bank account details", "Property documents", "Construction estimate"],
    officialPortal: "https://pmaymis.gov.in",
    fee: "Subsidized",
    category: "welfare",
  },
  {
    id: "sch-swachh",
    type: "scheme",
    name: "Swachh Bharat Mission",
    nameHindi: "स्वच्छ भारत मिशन",
    department: "Ministry of Jal Shakti",
    description: "Swachh Bharat Mission aims to achieve universal sanitation coverage and make India open defecation free.",
    keywords: ["swachh bharat", "toilet", "sanitation", "open defecation", "toilet construction", "sbm", "clean india", "厕所", "shouchalay", "individual household latrine"],
    eligibility: ["BPL families", "Households without toilet facility"],
    benefits: ["₹12,000 subsidy for toilet construction", "Community toilet facilities", "Solid waste management"],
    requiredDocuments: ["Aadhaar card", "BPL certificate", "Bank account details", "Land ownership proof"],
    officialPortal: "https://swachhbharatmis.gov.in",
    fee: "Free (subsidy provided)",
    category: "welfare",
  },

  // ═══════════════════════════════════════════════════════════════
  // PENSION & SOCIAL SECURITY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "sch-atal-pension",
    type: "scheme",
    name: "Atal Pension Yojana",
    nameHindi: "अटल पेंशन योजना",
    department: "Ministry of Finance / PFRDA",
    description: "Atal Pension Yojana provides guaranteed minimum pension of ₹1,000 to ₹5,000 per month after age 60 for unorganized sector workers.",
    keywords: ["atal pension", "pension", "retirement", "old age", "pension scheme", "unorganized sector", "guaranteed pension", "apy", "nps"],
    eligibility: ["Indian citizens aged 18-40", "Bank account linked with Aadhaar", "Not covered under any statutory social security scheme"],
    benefits: ["Guaranteed pension ₹1,000-₹5,000/month", "Government co-contribution", "Tax benefits under Section 80CCD"],
    requiredDocuments: ["Aadhaar card", "Bank account details", "Mobile number"],
    officialPortal: "https://www.jansuraksha.gov.in",
    fee: "Age-based monthly contribution",
    category: "welfare",
  },
  {
    id: "sch-jeevan",
    type: "scheme",
    name: "Pradhan Mantri Jeevan Jyoti & Suraksha Bima",
    nameHindi: "प्रधानमंत्री जीवन ज्योति एवं सुरक्षा बीमा",
    department: "Ministry of Finance",
    description: "Low-cost life insurance (JJBY: ₹436/year for ₹2 lakh cover) and accident insurance (PMSBY: ₹20/year for ₹2 lakh cover) for citizens.",
    keywords: ["jeevan jyoti", "suraksha bima", "life insurance", "accident insurance", "pmjjby", "pmsby", "cheap insurance", "government insurance", "bima", "insurance scheme"],
    eligibility: ["Age 18-50 (JJBY)", "Age 18-70 (PMSBY)", "Bank account holder"],
    benefits: ["₹2 lakh life insurance at ₹436/year", "₹2 lakh accident insurance at ₹20/year", "Auto-debit from bank account"],
    requiredDocuments: ["Aadhaar card", "Bank account details", "Nominee details"],
    fee: "₹436/year (JJBY) / ₹20/year (PMSBY)",
    category: "welfare",
  },

  // ═══════════════════════════════════════════════════════════════
  // DIGITAL & TECHNOLOGY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "info-digiLocker",
    type: "info",
    name: "DigiLocker",
    nameHindi: "डिजीलॉकर",
    department: "Ministry of Electronics & IT (MeitY)",
    description: "DigiLocker is a digital document wallet for storing and sharing verified government-issued documents. Documents in DigiLocker are legally at par with originals.",
    keywords: ["digilocker", "digital locker", "digital documents", "online documents", "e documents", "digital id", "paperless", "verified documents", "legally valid"],
    eligibility: ["Any Indian citizen with Aadhaar"],
    benefits: ["Store 10GB of documents", "Legally valid documents", "Share verified documents with agencies", "Access from anywhere", "Auto-fetch from issuing authorities"],
    requiredDocuments: ["Aadhaar card linked mobile number"],
    officialPortal: "https://digilocker.gov.in",
    fee: "Free",
    category: "info",
  },
  {
    id: "info-umang",
    type: "info",
    name: "UMANG App",
    nameHindi: "उमंग ऐप",
    department: "Ministry of Electronics & IT (MeitY)",
    description: "Unified Mobile Application for New-age Governance (UMANG) provides access to 1,200+ government services on a single mobile platform.",
    keywords: ["umang", "government app", "mobile app", "government services app", "all services app", "digital india app"],
    eligibility: ["Any Indian citizen"],
    benefits: ["Access 1,200+ services", "Single login for all services", "Aadhaar-based authentication", "Track applications", "Pay fees online"],
    requiredDocuments: ["Mobile number", "Aadhaar (for Aadhaar-based services)"],
    officialPortal: "https://web.umang.gov.in",
    fee: "Free",
    category: "info",
  },
  {
    id: "info-cowin",
    type: "info",
    name: "Co-WIN Vaccination",
    nameHindi: "को-विन",
    department: "Ministry of Health & Family Welfare",
    description: "Co-WIN is the digital platform for COVID-19 vaccination registration, scheduling, and certificate download.",
    keywords: ["cowin", "covid vaccine", "vaccination", "vaccine certificate", "dose", "booster", "covid registration", "vaccination center"],
    eligibility: ["All Indian citizens aged 12+"],
    benefits: ["Online registration", "Slot booking at nearby centers", "Digital vaccination certificate", "International travel certificate"],
    requiredDocuments: ["Aadhaar card or any photo ID", "Mobile number"],
    officialPortal: "https://www.cowin.gov.in",
    fee: "Free (government centers)",
    category: "info",
  },

  // ═══════════════════════════════════════════════════════════════
  // ENVIRONMENT & LAND
  // ═══════════════════════════════════════════════════════════════
  {
    id: "svc-environment",
    type: "service",
    name: "Environmental Clearance",
    nameHindi: "पर्यावरण मंजूरी",
    department: "Ministry of Environment, Forest & Climate Change",
    description: "Environmental clearance is required for projects that may have environmental impact. Mandatory for construction, mining, and industrial projects.",
    keywords: ["environment", "environmental clearance", "pollution", "noc pollution", "pollution control board", "efactory", "ec", "green clearance", "consent to operate", "consent to establish"],
    eligibility: ["Projects listed in EIA notification 2006", "Construction projects above 20,000 sq m"],
    requiredDocuments: ["Project report", "Environmental impact assessment", "Land documents", "Consent from pollution control board"],
    estimatedDays: 30,
    category: "environment",
  },
  {
    id: "svc-water",
    type: "service",
    name: "Water Connection",
    nameHindi: "जल कनेक्शन",
    department: "Municipal Corporation / Water Supply Department",
    description: "Apply for new water connection from municipal water supply. Includes piped water under Jal Jeevan Mission for rural areas.",
    keywords: ["water", "water connection", "jal jeevan", "tap water", "water supply", "pipeline", "water tap", " drinking water"],
    eligibility: ["Household within municipal limits", "Rural household under Jal Jeevan Mission"],
    requiredDocuments: ["Property ownership proof", "Aadhaar card", "Building plan approval", "NOC from neighbors"],
    estimatedDays: 15,
    category: "utility",
  },
  {
    id: "svc-electricity",
    type: "service",
    name: "Electricity Connection",
    nameHindi: "बिजली कनेक्शन",
    department: "State Electricity Board / DISCOM",
    description: "Apply for new electricity connection from the state distribution company (DISCOM). Includes solar rooftop connections.",
    keywords: ["electricity", "power connection", "bijli", "light connection", "new connection", "solar rooftop", "discom", "electricity board", "meter"],
    eligibility: ["Property owner or tenant with owner consent", "Within DISCOM service area"],
    requiredDocuments: ["Property ownership/lease proof", "Aadhaar card", "Building plan approval", "NOC from society/building"],
    estimatedDays: 7,
    fee: "Security deposit varies by state",
    category: "utility",
  },
];

// ─── FAQ Responses for common citizen questions ──────────────

export const FAQ_RESPONSES: Record<string, string> = {
  "what is onegov": "ONEGOV is a unified government-service orchestration platform developed under India's Digital India initiative. It connects citizens with multiple government departments through a single interface, so you don't need to visit multiple portals or offices.\n\n**Key Features:**\n• Natural language AI assistant\n• Unified application tracking\n• Document reuse across services\n• Consent-based data sharing\n• Real-time status updates",
  "what services are available": "ONEGOV currently supports **20+ government services** across 10 departments:\n\n**Identity Documents:**\n• Aadhaar Card (UIDAI)\n• PAN Card (Income Tax)\n• Passport (MEA)\n• Driving License (Parivahan)\n• Voter ID (ECI)\n\n**Business:**\n• Business Registration (MCA)\n• GST Registration (GSTN)\n• FSSAI Food License\n• MSME/Udyam Registration\n• MUDRA Loan\n\n**Civil Documents:**\n• Birth Certificate\n• Death Certificate\n• Marriage Registration\n• Income Certificate\n• Caste Certificate\n\n**Property:**\n• Property Registration\n• 7/12 Extract\n\n**Welfare Schemes:**\n• PM-KISAN\n• Ayushman Bharat\n• Ujjwala Yojana\n• Jan Dhan Yojana\n• And many more...\n\nWhich service would you like help with?",
  "how does onegov work": "ONEGOV works in **4 simple steps:**\n\n1. **Tell us your goal** — Describe what you want in natural language\n2. **We build your roadmap** — AI identifies all required services and creates a step-by-step plan\n3. **Complete each step** — Upload documents, fill forms, and submit applications\n4. **Track everything** — Monitor all your applications from one dashboard\n\nBehind the scenes, ONEGOV coordinates with multiple government departments through our interoperability framework.",
  "is onegov government website": "ONEGOV is a prototype platform developed for **Smart India Hackathon 2026** (Problem Statement SIH26129). It demonstrates how a unified government service platform could work.\n\nIn production, it would be deployed as an official government service under the Digital India programme of the Ministry of Electronics & IT (MeitY).",
  "what is rti": "**Right to Information (RTI) Act, 2005**\n\nEvery Indian citizen has the right to request information from any public authority. The government must respond within **30 days**.\n\n**How to file RTI:**\n1. Go to **rtionline.gov.in**\n2. Select the public authority (ministry/department)\n3. Write your question clearly\n4. Pay ₹10 fee\n5. Submit\n\n**Helpline:** 1800-11-0031\n\nRTI is a powerful tool for transparency and accountability.",
  "how to file complaint": "**File a grievance through CPGRAMS:**\n\n1. Visit **pgportal.gov.in**\n2. Register/Login\n3. Select the ministry/department\n4. Describe your grievance\n5. Attach supporting documents\n6. Submit\n\nYou'll receive a registration number to track status. The department must resolve your grievance within **30 days**.\n\n**Alternative:** You can also file through ONEGOV's integrated grievance system.",
  "what documents do i need": "The documents needed depend on the service you're applying for. Here are the most commonly required ones:\n\n**Universal Documents (needed for most services):**\n• Aadhaar Card\n• PAN Card\n• Passport-size Photograph\n• Address Proof\n\n**For Business:**\n• Business Registration Certificate\n• Partnership/MOA documents\n• Bank Account details\n\n**For Identity:**\n• Birth Certificate\n• Previous address proof\n\nTell me which service you need, and I'll list the exact documents required.",
  "how to link aadhaar pan": "**Link Aadhaar with PAN:**\n\n1. Visit **incometax.gov.in**\n2. Go to 'Link Aadhaar' under Quick Links\n3. Enter PAN and Aadhaar number\n4. Submit\n\n**Or SMS:** Send `UIDPAN <12-digit Aadhaar> <10-digit PAN>` to 567678\n\n**Or by post:** Send copy of Aadhaar and PAN to CPC, PO Box No. 1, Electronic City Post Office, Bengaluru — 560100\n\n**Deadline:** As per latest notification, linking is mandatory to avoid PAN becoming inoperative.",
  "minimum wage": "**Minimum Wages in India (vary by state and skill level):**\n\n**Unskilled:** ₹500 - ₹800 per day\n**Semi-skilled:** ₹600 - ₹1,000 per day\n**Skilled:** ₹700 - ₹1,200 per day\n\n**Examples by state (2024-25):**\n• Maharashtra: ₹550 (unskilled) to ₹900 (skilled)\n• Delhi: ₹600 to ₹1,000\n• Karnataka: ₹520 to ₹850\n\nCheck your state's labour department website for exact current rates.",
  "how to check property online": "**Check Property Records Online:**\n\n**Maharashtra:**\n• Visit digitize.mahabhumi.gov.in\n• Search by survey number or name\n• View 7/12 extract, property card\n\n**Other States:**\n• Visit your state's land records portal\n• Search by survey/plot number\n\n**All India (DILRMP):**\n• Visit lrc.gov.in\n• Check land records digitally\n\nYou can also visit your nearest Tehsildar office for certified copies.",
  "pm kisan status": "**Check PM-KISAN Status:**\n\n1. Visit **pmkisan.gov.in**\n2. Click 'Beneficiary Status'\n3. Enter Aadhaar number or bank account number\n4. Click 'Get Data'\n\nYou can see:\n• Your installment status\n• Payment dates\n• Bank account details\n\n**Helpline:** 1800-180-1551\n\nIf you're not receiving payments, check if your Aadhaar is linked to your bank account.",
  "gst filing": "**GST Return Filing:**\n\n**GSTR-1 (Outward supplies):** Due 11th of next month\n**GSTR-3B (Summary return):** Due 20th of next month\n\n**Steps:**\n1. Login to **gst.gov.in**\n2. Go to Services → Returns\n3. Select return type\n4. Fill in details\n5. Submit\n\n**Late fee:** ₹50/day (CGST + SGST) for GSTR-3B\n\nFor small businesses (turnover < ₹1.5 crore), quarterly filing is available under QRMP scheme.",
  "passport police verification": "**Passport Police Verification Process:**\n\n1. After passport application, police verification is initiated\n2. Local police station verifies your identity and address\n3. You'll receive an SMS with verification date\n4. Keep documents ready: Aadhaar, address proof, photographs\n5. Police submits report within **21 days**\n\n**If police doesn't come:**\n• Visit your local police station\n• File complaint on passport seva portal\n• Call helpline: 1800-258-1800\n\n**Note:** For Tatkal passport, verification may be post-issuance.",
  "how to get income certificate": "**Income Certificate Process:**\n\n1. Visit your nearest **Tehsildar/Taluka office**\n2. Fill Form 16 or the prescribed application\n3. Attach:\n   • Aadhaar card\n   • Salary slips or Form 16 (IT return)\n   • Bank statement (6 months)\n   • Self-declaration/affidavit\n4. Pay ₹10-50 fee\n5. Certificate issued in 3-7 working days\n\n**Online (some states):**\n• Maharashtra: aaplesarkar.mahaonline.gov.in\n• Apply through ONEGOV for faster processing",
  "caste certificate for reservation": "**Caste Certificate for Reservation:**\n\n**Who needs it:** SC/ST/OBC candidates for:\n• Government job reservations\n• Educational admissions\n• Scholarship applications\n\n**Process:**\n1. Apply at Tehsildar office or online portal\n2. Submit:\n   • Aadhaar card\n   • School leaving certificate\n   • Parent's caste certificate\n   • Affidavit on stamp paper\n3. Verification by revenue officer\n4. Certificate issued in 7-15 days\n\n**OBC Certificate:** Also requires 'non-creamy layer' certificate for central government jobs.",
  "ration card apply online": "**Apply for Ration Card Online:**\n\n**Steps:**\n1. Visit your state's food department portal\n   • Maharashtra: mera.ration.up.gov.in\n   • Karnataka: ahara.kar.nic.in\n2. Register with Aadhaar and mobile number\n3. Fill family details\n4. Upload documents\n5. Submit application\n\n**Documents needed:**\n• Aadhaar (all family members)\n• Address proof\n• Income certificate\n• Bank account details\n• Gas connection proof\n\n**Types:**\n• APL (Above Poverty Line)\n• BPL (Below Poverty Line)\n• Antyodaya (Poorest of poor)",
  "vehicle registration": "**Vehicle Registration on Parivahan:**\n\n1. Purchase vehicle from dealer (dealer handles Form 20/21)\n2. Visit RTO or apply online on **parivahan.gov.in**\n3. Submit:\n   • Sale invoice\n   • Insurance certificate\n   • Pollution certificate\n   • Address proof\n   • Aadhaar card\n4. Pay road tax and registration fee\n5. Receive RC (Registration Certificate)\n\n**Fees:**\n• Two-wheeler: ₹1,000-₹3,000\n• Four-wheeler: ₹3,000-₹15,000\n• Commercial: Higher rates\n\n**Validity:** 15 years for private vehicles, 5 years for commercial.",
};

// ─── Government Official Tone Templates ──────────────────────

export const OFFICIAL_TEMPLATES = {
  greeting: `Namaskar! 🙏 Welcome to ONEGOV — your unified government service assistant.

I am here to help you navigate government services efficiently. Whether you need identity documents, want to start a business, apply for certificates, or check on welfare schemes — I can guide you through the entire process.

**How may I assist you today?**`,
  
  schemeIntroduction: (schemeName: string, dept: string) => 
    `The **${schemeName}** is administered by the ${dept}. Let me provide you with accurate information about this initiative.`,

  documentList: (docs: string[]) => 
    `The following documents are required:\n${docs.map((d, i) => `${i + 1}. ${d}`).join("\n")}\n\n*Please ensure all documents are original and self-attested copies are ready.*`,

  helplineInfo: (name: string, phone: string) => 
    `For **${name}**, you can reach the helpline at **${phone}** (toll-free). Our officers are available Monday to Saturday, 9:30 AM to 6:00 PM.`,

  disclaimer: `\n\n*This information is provided based on verified government data. For the most current details, please visit the official portal or contact the department helpline.*`,
};
